import Navbar from '@/components/views/Navbar'
import './globals.css'
import { Maven_Pro, Roboto } from 'next/font/google'
import Wrapper from '@/components/shared/Wrapper'
import Footer from '@/components/views/Footer'
import Providers from '@/components/shared/Provider'
const inter  = Maven_Pro ({subsets: ['latin'],
weight: ["400", "500", "600" , "700", "800" , "900"]
})
export const metadata = {
  title: 'E-Commerce',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <Wrapper>
          <Providers>
        <Navbar/>
       <div className='min-h-screen'> {children}
       </div>
        <Footer/>
        </Providers>
        </Wrapper>
        </body>
    </html>
  )
}
